### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by c0ldn3s5** [revengsmK/sunlock11#1]
doesnt work

**Comment by revengsmK** [comment]
Hi c0ldn3s5,

I've tested sunlock11 on the latest, fully updated Windows 11 Pro 23H2 (OS Build 22631.3155), and it works.

**Comment by camaleaoninja** [comment]
It is not working for me because it not extract as a .exe arquive, how do you convert sunlock.c to sunlock.exe?

**Comment by revengsmK** [comment]
Hi camaleaoninja,

You can download .exe file from here:

https://github.com/revengsmK/sunlock11/releases/tag/v0.1

**Comment by revengsmK** [comment]
sunlock11 is working.
